### ISSUE TITLE
ONT compatibility

### ISSUE THREAD

**Issue by racng** [jeffhussmann/knock-knock#15]
I am trying to run knock-knock nanopore long reads.
I tired specifying 'ont' as a platform but it doesn't work, since it doesn't have its own Experiment class. 
I am guessing the most important change is the parameters used for minimap2? 
I think a quick fix would be to build a minimap2 index using the `-x map-ont` prefix, and then specify its path as the minimap index in index_locations.yaml and still specify `pacbio`  as the platform in the `sample_sheet.csv`. 
I also removed `-H` option when building the index since the minimap2 github says "The difference between map-pb and map-ont is that map-pb uses homopolymer-compressed (HPC) minimizers as seeds, while map-ont uses ordinary minimizers as seeds. Empirical evaluation suggests HPC minimizers improve performance and sensitivity when aligning PacBio CLR reads, but hurt when aligning Nanopore reads."

```bash
minimap2 -x map-ont -d $PROJ/indices/hg38/minimap2_ont/hg38.mmi \
    $PROJ/indices/hg38/fasta/hg38.fa 
```

index_locations.yaml
```yaml
hg38: 
  STAR: "project_path/indices/hg38/STAR"
  fasta: "project_path/indices/hg38/fasta"
  minimap2: "project_path/indices/hg38/minimap2_ont/hg38.mmi"
```

Is there anything in the pipeline that needs to be changed?
